In [2]:
import pandas as pd

In [4]:
reliance_df = pd.read_csv('../data/raw/RELIANCE_stock_data.csv')
infy_df     = pd.read_csv('../data/raw/INFY_stock_data.csv')
tcs_df      = pd.read_csv('../data/raw/TCS_stock_data.csv')
hdfcbank_df = pd.read_csv('../data/raw/HDFCBANK_stock_data.csv')

In [14]:
tickers = ['RELIANCE', 'INFY', 'TCS', 'HDFCBANK']

stock_df = pd.concat([reliance_df, infy_df, tcs_df, hdfcbank_df], keys=tickers).reset_index(level=0).rename(columns={'level_0': 'Ticker'})
stock_df

,Ticker,Date,Close,High,Low,Open,Volume
0,RELIANCE,2024-05-27,1455.477417,1473.990419,1450.811997,1469.349718,6629010
1,RELIANCE,2024-05-28,1445.501221,1467.637431,1442.076616,1457.214574,7820162
2,RELIANCE,2024-05-29,1430.189575,1447.287998,1427.881584,1435.872489,7383556
3,RELIANCE,2024-05-30,1414.381470,1429.817271,1409.666368,1424.953247,13206858
4,RELIANCE,2024-05-31,1419.890747,1431.653660,1411.800602,1420.784159,31069832
...,...,...,...,...,...,...,...
493,HDFCBANK,2026-05-21,759.150024,768.250000,755.150024,767.000000,34664725
494,HDFCBANK,2026-05-22,766.799988,775.000000,759.150024,759.150024,25604071
495,HDFCBANK,2026-05-25,786.849976,787.849976,775.200012,776.000000,26043952
496,HDFCBANK,2026-05-26,778.900024,790.849976,776.750000,784.049988,31528062
497,HDFCBANK,2026-05-27,765.599976,773.900024,761.250000,769.500000,25443928

# Creating basic features

In [29]:
# Daily returns
stock_df['Daily_Return'] = stock_df.groupby('Ticker')['Close'].pct_change()
stock_df.fillna(0, inplace=True)

# Moving averages for 7, 14 and 30 days
stock_df['MA_7'] = stock_df.groupby('Ticker')['Close'].transform(lambda x: x.rolling(window=7).mean())
stock_df['MA_14'] = stock_df.groupby('Ticker')['Close'].transform(lambda x: x.rolling(window=14).mean())
stock_df['MA_30'] = stock_df.groupby('Ticker')['Close'].transform(lambda x: x.rolling(window=30).mean())

# Volatility (standard deviation of daily returns) over a 30-day window
stock_df['Volatility_30'] = stock_df.groupby('Ticker')['Daily_Return'].transform(lambda x: x.rolling(window=30).std())

# Volume change
stock_df['Volume_Change'] = stock_df.groupby('Ticker')['Volume'].pct_change()

stock_df.head(50)

,Ticker,Date,Close,High,Low,Open,Volume,Daily_Return,MA_7,MA_14,MA_30,Volatility_30,Volume_Change,Price_Movement
0,RELIANCE,2024-05-27,1455.477417,1473.990419,1450.811997,1469.349718,6629010,0.000000,NaN,NaN,NaN,NaN,NaN,0
1,RELIANCE,2024-05-28,1445.501221,1467.637431,1442.076616,1457.214574,7820162,-0.006854,NaN,NaN,NaN,NaN,0.179688,0
2,RELIANCE,2024-05-29,1430.189575,1447.287998,1427.881584,1435.872489,7383556,-0.010593,NaN,NaN,NaN,NaN,-0.055831,0
3,RELIANCE,2024-05-30,1414.381470,1429.817271,1409.666368,1424.953247,13206858,-0.011053,NaN,NaN,NaN,NaN,0.788685,1
4,RELIANCE,2024-05-31,1419.890747,1431.653660,1411.800602,1420.784159,31069832,0.003895,NaN,NaN,NaN,NaN,1.352553,1
5,RELIANCE,2024-06-03,1499.228516,1503.372890,1448.280652,1472.104322,21527942,0.055876,NaN,NaN,NaN,NaN,-0.307111,0
6,RELIANCE,2024-06-04,1387.009155,1487.043779,1349.313184,1487.043779,36709098,-0.074851,1435.954014,NaN,NaN,NaN,0.705184,1
7,RELIANCE,2024-06-05,1410.311646,1420.635260,1373.930892,1411.552462,17464890,0.016801,1429.501761,NaN,NaN,NaN,-0.524235,1
8,RELIANCE,2024-06-06,1421.081909,1433.092985,1410.907217,1424.456953,17855722,0.007637,1426.013288,NaN,NaN,NaN,0.022378,1
9,RELIANCE,2024-06-07,1459.150024,1461.185011,1416.019306,1418.004612,18558696,0.026788,1430.150495,NaN,NaN,NaN,0.039370,1
10,RELIANCE,2024-06-10,1460.589478,1482.378160,1457.288834,1459.150058,9251760,0.000987,1436.751639,NaN,NaN,NaN,-0.501487,0
11,RELIANCE,2024-06-11,1445.972778,1462.847878,1443.987472,1458.207177,11774902,-0.010007,1440.477644,NaN,NaN,NaN,0.272720,1
12,RELIANCE,2024-06-12,1452.573730,1465.155654,1444.483706,1446.791576,10081742,0.004565,1433.812674,NaN,NaN,NaN,-0.143794,1
13,RELIANCE,2024-06-13,1454.484741,1461.433312,1449.372554,1461.185149,9181160,0.001316,1443.452044,1439.703029,NaN,NaN,-0.089328,1
14,RELIANCE,2024-06-14,1466.694458,1468.803846,1446.518713,1459.199880,8157998,0.008395,1451.506731,1440.504246,NaN,NaN,-0.111441,1
15,RELIANCE,2024-06-18,1470.143921,1476.472084,1460.539955,1476.422403,7196766,0.002352,1458.515590,1442.264439,NaN,NaN,-0.117827,0
16,RELIANCE,2024-06-19,1447.933228,1476.571240,1445.302673,1476.571240,8725874,-0.015108,1456.913191,1443.531843,NaN,NaN,0.212472,1
17,RELIANCE,2024-06-20,1462.872559,1471.955357,1439.445974,1448.280609,16113776,0.010318,1457.239345,1446.995492,NaN,NaN,0.846666,0
18,RELIANCE,2024-06-21,1443.515869,1463.865255,1429.990973,1462.798201,31170360,-0.013232,1456.888358,1448.683001,NaN,NaN,0.934392,0
19,RELIANCE,2024-06-24,1430.884277,1438.850341,1426.938506,1434.904570,8878386,-0.008751,1453.789865,1443.801270,NaN,NaN,-0.715166,1
20,RELIANCE,2024-06-25,1443.466309,1445.228292,1430.412898,1432.398204,7045386,0.008793,1452.215803,1447.833923,NaN,NaN,-0.206456,1
21,RELIANCE,2024-06-26,1502.901367,1507.814951,1434.507557,1435.425809,22014882,0.041175,1457.388218,1454.447475,NaN,NaN,2.124723,1
22,RELIANCE,2024-06-27,1519.305054,1526.203943,1494.935375,1502.628435,28383030,0.010915,1464.411237,1461.463414,NaN,NaN,0.289266,1
23,RELIANCE,2024-06-28,1553.898926,1569.384287,1519.776481,1519.776481,28957336,0.022770,1479.549194,1468.231192,NaN,NaN,0.020234,0
24,RELIANCE,2024-07-01,1548.687500,1567.796069,1544.245402,1551.045051,7724306,-0.003354,1491.808472,1474.523908,NaN,NaN,-0.733252,1
25,RELIANCE,2024-07-02,1553.675537,1561.939324,1545.560551,1557.968712,7749246,0.003221,1507.545567,1482.216963,NaN,NaN,0.003229,0
26,RELIANCE,2024-07-03,1541.019287,1563.428379,1531.440162,1554.817066,9049620,-0.008146,1523.279140,1488.534502,NaN,NaN,0.167807,1
27,RELIANCE,2024-07-04,1542.607544,1555.983518,1539.406262,1545.560662,6837176,0.001031,1537.442174,1494.828988,NaN,NaN,-0.244479,1
28,RELIANCE,2024-07-05,1576.953247,1586.755695,1536.626722,1542.408877,12269710,0.022265,1548.021014,1502.704616,NaN,NaN,0.794558,1
29,RELIANCE,2024-07-08,1589.138062,1596.980044,1570.898064,1577.325468,9500806,0.007727,1557.997158,1511.204197,1474.984652,0.021672,-0.225670,0
30,RELIANCE,2024-07-09,1578.591187,1588.741039,1568.887980,1585.862321,6960002,-0.006637,1561.524623,1520.536909,1479.088444,0.021739,-0.267430,0
31,RELIANCE,2024-07-10,1572.585571,1585.763063,1551.665459,1583.281431,7134578,-0.003804,1564.938634,1528.373553,1483.324589,0.021699,0.025083,0
32,RELIANCE,2024-07-11,1569.036865,1592.463450,1558.961414,1575.836514,11940946,-0.002257,1567.133109,1537.339338,1487.952832,0.021571,0.673672,1
33,RELIANCE,2024-07-12,1584.993774,1593.356924,1562.932087,1572.858616,12924784,0.010170,1573.415179,1548.347159,1493.639909,0.021431,0.082392,1
34,RELIANCE,2024-07-15,1585.490112,1594.051744,1573.851280,1592.662006,5329688,0.000313,1579.541260,1558.491717,1499.159888,0.021442,-0.587638,0
35,RELIANCE,2024-07-16,1564.669189,1588.244697,1557.596537,1581.792453,9386838,-0.013132,1577.786394,1562.903704,1501.341243,0.019266,0.761236,1
36,RELIANCE,2024-07-18,1575.017700,1582.189594,1546.379565,1564.421081,12298374,0.006614,1575.769200,1566.883179,1507.608195,0.012760,0.310172,0
37,RELIANCE,2024-07-19,1543.724243,1578.293333,1541.391533,1574.347562,13140390,-0.019869,1570.788208,1566.156416,1512.055282,0.013269,0.068466,0
38,RELIANCE,2024-07-22,1489.649536,1526.203933,1488.259798,1525.955770,19674376,-0.035029,1558.940203,1561.939418,1514.340869,0.014947,0.497244,0
39,RELIANCE,2024-07-23,1476.968262,1494.687092,1452.251180,1489.971990,18052044,-0.008513,1545.787545,1556.460327,1514.934810,0.014277,-0.082459,1
40,RELIANCE,2024-07-24,1484.710938,1498.409596,1465.552809,1474.089600,11913362,0.005242,1531.461426,1552.438302,1515.738859,0.014303,-0.340055,0
41,RELIANCE,2024-07-25,1481.435303,1489.450927,1466.222823,1470.119035,12519876,-0.002206,1516.596453,1548.068856,1516.920943,0.014173,0.050910,1
42,RELIANCE,2024-07-26,1497.938110,1501.313155,1479.400268,1481.435255,9859940,0.011140,1507.063442,1542.424918,1518.433089,0.014282,-0.212457,1
43,RELIANCE,2024-07-29,1508.931641,1516.277296,1500.667854,1500.841495,7538550,0.007339,1497.622576,1536.695888,1520.247986,0.014327,-0.235437,0
44,RELIANCE,2024-07-30,1502.032837,1513.795750,1498.905956,1505.879367,8228208,-0.004572,1491.666661,1531.227434,1521.425932,0.014302,0.091484,0
45,RELIANCE,2024-07-31,1494.364502,1499.352486,1490.120887,1492.949923,10057346,-0.005105,1492.340227,1525.640215,1522.233285,0.014340,0.222301,1
46,RELIANCE,2024-08-01,1504.167114,1506.847229,1493.247931,1500.891311,10764222,0.006560,1496.225778,1521.006662,1524.107747,0.014062,0.070285,0
47,RELIANCE,2024-08-02,1488.309326,1498.235856,1482.303849,1493.942680,10268248,-0.010543,1496.739833,1514.100630,1524.955640,0.014120,-0.046076,0
48,RELIANCE,2024-08-05,1436.691406,1472.997761,1422.719864,1469.126390,17046704,-0.034682,1490.347848,1503.472151,1524.728158,0.015339,0.660138,1
49,RELIANCE,2024-08-06,1445.352295,1466.644651,1440.661913,1444.458883,10236186,0.006028,1482.835589,1494.949515,1525.210425,0.015287,-0.399521,1

# Creating target label

In [30]:
# Create a target variable for stock price movement (1 for up, 0 for down)
stock_df['Price_Movement'] = (stock_df.groupby('Ticker')['Close'].shift(-1) > stock_df['Close']).astype(int)

stock_df

,Ticker,Date,Close,High,Low,Open,Volume,Daily_Return,MA_7,MA_14,MA_30,Volatility_30,Volume_Change,Price_Movement
0,RELIANCE,2024-05-27,1455.477417,1473.990419,1450.811997,1469.349718,6629010,0.000000,NaN,NaN,NaN,NaN,NaN,0
1,RELIANCE,2024-05-28,1445.501221,1467.637431,1442.076616,1457.214574,7820162,-0.006854,NaN,NaN,NaN,NaN,0.179688,0
2,RELIANCE,2024-05-29,1430.189575,1447.287998,1427.881584,1435.872489,7383556,-0.010593,NaN,NaN,NaN,NaN,-0.055831,0
3,RELIANCE,2024-05-30,1414.381470,1429.817271,1409.666368,1424.953247,13206858,-0.011053,NaN,NaN,NaN,NaN,0.788685,1
4,RELIANCE,2024-05-31,1419.890747,1431.653660,1411.800602,1420.784159,31069832,0.003895,NaN,NaN,NaN,NaN,1.352553,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,HDFCBANK,2026-05-21,759.150024,768.250000,755.150024,767.000000,34664725,-0.000461,762.342861,769.689287,781.821670,0.014474,0.443554,1
494,HDFCBANK,2026-05-22,766.799988,775.000000,759.150024,759.150024,25604071,0.010077,764.800005,768.789285,780.791669,0.014122,-0.261380,1
495,HDFCBANK,2026-05-25,786.849976,787.849976,775.200012,776.000000,26043952,0.026148,767.271432,769.828570,780.010002,0.014668,0.017180,0
496,HDFCBANK,2026-05-26,778.900024,790.849976,776.750000,784.049988,31528062,-0.010104,768.900007,768.567858,779.483335,0.014365,0.210571,0
497,HDFCBANK,2026-05-27,765.599976,773.900024,761.250000,769.500000,25443928,-0.017075,768.464286,766.392857,778.006667,0.014173,-0.192975,0

# Save dataframe as a CSV file

In [31]:
stock_df.to_csv('../data/processed/stock_features.csv', index=False)