In [1]:
import pandas as pd
import yfinance as yf

In [2]:
dir(yf)

['AsyncWebSocket',
 'Auth',
 'Calendars',
 'ETFQuery',
 'EquityQuery',
 'FundQuery',
 'Industry',
 'Lookup',
 'Market',
 'MarketRegion',
 'PREDEFINED_SCREENER_QUERIES',
 'Search',
 'Sector',
 'Ticker',
 'Tickers',
 'WebSocket',
 '_NOTSET',
 '__all__',
 '__author__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_http',
 'base',
 'cache',
 'calendars',
 'config',
 'const',
 'data',
 'domain',
 'download',
 'enable_debug_mode',
 'exceptions',
 'live',
 'lookup',
 'multi',
 'pricing_pb2',
 'scrapers',
 'screen',
 'screener',
 'search',
 'set_config',
 'set_tz_cache_location',
 'ticker',
 'tickers',
 'utils',
 'version',
 'warnings']

In [3]:
tdg = yf.Ticker("TDG")

In [4]:
tdg

yfinance.Ticker object <TDG>

In [9]:
data = tdg.history(interval = '1m', start = '2022-01-03', end = '2022-01-10')

$TDG: possibly delisted; no price data found  (1m 2022-01-03 -> 2022-01-10) (Yahoo error = "1m data not available for startTime=1641186000 and endTime=1641790800. The requested range must be within the last 30 days.")

In [6]:
data.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-04-27 00:00:00-04:00,1146.400024,1165.900024,1146.400024,1158.359985,321200,0.0,0.0
2026-04-28 00:00:00-04:00,1167.540039,1173.000000,1136.359985,1154.060059,291300,0.0,0.0
2026-04-29 00:00:00-04:00,1154.209961,1155.000000,1128.209961,1142.739990,331500,0.0,0.0
2026-04-30 00:00:00-04:00,1143.459961,1164.369995,1141.949951,1159.979980,343500,0.0,0.0
2026-05-01 00:00:00-04:00,1171.579956,1171.670044,1145.920044,1154.449951,311000,0.0,0.0

In [15]:
df = pd.read_csv('../data/raw/TCS_stock_data.csv')
df

,index,Close,High,Low,Open,Volume
0,NaN,TCS.NS,TCS.NS,TCS.NS,TCS.NS,TCS.NS
1,2024-05-27,3585.412109375,3642.5431408365193,3580.099811979568,3592.8213842320465,1841538
2,2024-05-28,3578.748046875,3606.8010348271864,3569.5214375679907,3595.617155649428,1801993
3,2024-05-29,3544.963623046875,3587.1361699587314,3541.5619506089633,3587.1361699587314,1568095
4,2024-05-30,3482.0078125,3536.342645636951,3462.7620831275535,3520.126111198893,2919230
...,...,...,...,...,...,...
494,2026-05-21,2296.0673828125,2304.650948701518,2283.0440165455843,2299.816595750975,3299087
495,2026-05-22,2286.300048828125,2308.696328282268,2277.223171267918,2299.9154856057353,2617262
496,2026-05-25,2308.199951171875,2326.10009765625,2293.0,2325.0,3298364
497,2026-05-26,2276.199951171875,2327.89990234375,2272.39990234375,2308.199951171875,3587597
498,2026-05-27,2274.800048828125,2292.89990234375,2260.89990234375,2275.0,1093889